<a href="https://colab.research.google.com/github/Eaimanjot-Singh/ucs420-/blob/main/assingment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Question 1

In [20]:
import pandas as pd

roll_number_str = "1024170140"
categories = ["billing", "account", "general"]

fixed_entries = [
    {"question": "what is the annual fee", "answer": "The annual fee is Rs 500.", "keywords": "fee cost price charge", "category": "billing"},
    {"question": "how to reset password", "answer": "Go to Settings > Reset Password.", "keywords": "password reset login", "category": "account"},
    {"question": "what are your working hours", "answer": "We are open 9 AM to 5 PM.", "keywords": "hours timing open time", "category": "general"},
    {"question": "how can i pay the fee", "answer": "You can pay via UPI, card, or net banking.", "keywords": "pay payment upi fee", "category": "billing"}
]

In [21]:
if not roll_number_str.isdigit() or len(roll_number_str) < 2:
    raise ValueError("Enter a valid roll number.")

first_digit, second_digit = map(int, roll_number_str[-2:])
dynamic_entries = []

def make_entry(digit, kind):
    category = categories[digit % len(categories)]
    if kind == 1:
        templates = {
            "billing": (f"When is payment {digit} due?", f"Payment {digit} is due on the {digit}th of each month.", f"payment due date {digit}"),
            "account": (f"How do I update my email for account {digit}?", f"Update the email from account settings for item {digit}.", f"email update account {digit}"),
            "general": (f"Where are service details for {digit}?", f"Service details for {digit} are in the website help section.", f"service details help {digit}")
        }
    else:
        templates = {
            "billing": (f"How do I request a refund for item {digit}?", f"Contact support to request a refund for item {digit}.", f"refund support transaction {digit}"),
            "account": (f"What if I forget username code {digit}?", f"Use the Forgot Username option for account item {digit}.", f"username forgot account {digit}"),
            "general": (f"What features were added for {digit}?", f"Check announcements for updates related to {digit}.", f"features updates announcements {digit}")
        }
    question, answer, keywords = templates[category]
    return {"question": question, "answer": answer, "keywords": keywords, "category": category}

dynamic_entries = [make_entry(first_digit, 1), make_entry(second_digit, 2)]
for item in dynamic_entries:
    print(item)

Generated Dynamic Entries:
{'question': 'Where can I find information about 8-related services?', 'answer': "Information about 8-related services is available on our website's help section.", 'keywords': 'information services help 8', 'category': 'general'}
{'question': 'Are there any new features related to digit 8?', 'answer': 'Yes, we recently launched new features involving digit 8; check our announcements.', 'keywords': 'new features updates announcements 8', 'category': 'general'}

In [22]:
all_entries = fixed_entries + dynamic_entries
df_faq = pd.DataFrame(all_entries)
display(df_faq)

Final FAQ DataFrame:

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,Where can I find information about 8-related s...,Information about 8-related services is availa...,information services help 8,general
5,Are there any new features related to digit 8?,"Yes, we recently launched new features involvi...",new features updates announcements 8,general

## Question 2

In [23]:
import re

def score_faq_entries(query, df):
    query_words = set(re.findall(r"[a-z0-9]+", query.lower()))
    scores = []

    for _, row in df.iterrows():
        entry_text = " ".join(str(row[field]) for field in ["question", "answer", "keywords"]).lower()
        entry_words = set(re.findall(r"[a-z0-9]+", entry_text))
        scores.append(len(query_words & entry_words))

    results = df.copy()
    results["confidence_score"] = scores
    results = results[results["confidence_score"] > 0]
    return results.sort_values("confidence_score", ascending=False).reset_index(drop=True)

for query in ["how to pay my fees", "reset my password please", "information about 8 services"]:
    print("Search query:", query)
    display(score_faq_entries(query, df_faq))

Scoring results for query: 'how to pay my fees'

,question,answer,keywords,category,confidence_score
0,how to reset password,Go to Settings > Reset Password.,password reset login,account,2
1,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing,2
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general,1
3,Are there any new features related to digit 8?,"Yes, we recently launched new features involvi...",new features updates announcements 8,general,1

Scoring results for query: 'reset my password please'

,question,answer,keywords,category,confidence_score
0,how to reset password,Go to Settings > Reset Password.,password reset login,account,2

Scoring results for query: 'information about 8 services'

,question,answer,keywords,category,confidence_score
0,Where can I find information about 8-related s...,Information about 8-related services is availa...,information services help 8,general,4
1,Are there any new features related to digit 8?,"Yes, we recently launched new features involvi...",new features updates announcements 8,general,1

## Question 3

In [24]:
def same_category(category_name, df):
    selected = df.loc[df["category"].str.casefold() == category_name.casefold(), "question"]
    return selected.tolist()

chosen_category = dynamic_entries[0]["category"]
for number, question in enumerate(same_category(chosen_category, df_faq), start=1):
    print(f"{number}. {question}")

Questions belonging to category 'general':
1. what are your working hours
2. Where can I find information about 8-related services?
3. Are there any new features related to digit 8?

## Question 4

In [25]:
entry_idx = 0
print("Before update:")
display(df_faq.iloc[entry_idx])

keyword = input("Enter a keyword to add: ").strip() or "discount"
current = df_faq.at[entry_idx, "keywords"]
words = current.split()
if keyword.lower() not in [word.lower() for word in words]:
    words.append(keyword)
    df_faq.at[entry_idx, "keywords"] = " ".join(words)

print("After update:")
display(df_faq.iloc[entry_idx])
csv_filename = f"{roll_number_str}_faq_data.csv"
df_faq.to_csv(csv_filename, index=False)
print("Saved file:", csv_filename)

Original Entry:
question       what is the annual fee
answer      The annual fee is Rs 500.
keywords        fee cost price charge
category                      billing
Name: 0, dtype: object
Enter a new keyword to add to this entry: hello

Updated Entry:
question         what is the annual fee
answer        The annual fee is Rs 500.
keywords    fee cost price charge hello
category                        billing
Name: 0, dtype: object

Successfully saved the updated FAQ DataFrame to 1024170188_faq_data.csv!

## Question 5

In [26]:
counts = df_faq["category"].value_counts().rename_axis("category").reset_index(name="count")
print("FAQ entries per category:")
display(counts)

FAQ Entries count per category:

  category  count
0  account      1
1  billing      2
2  general      3

## Question 6

In [27]:
def score_faq_entries_v2(query, df):
    ranked = score_faq_entries(query, df)
    if ranked.empty:
        print("No matching FAQ entries found.")
        return ranked

    best_score = ranked["confidence_score"].iloc[0]
    best_matches = ranked[ranked["confidence_score"] == best_score]
    if len(best_matches) > 1:
        print("More than one entry shares the best score:", best_score)
        display(best_matches)
    else:
        print("Best match score:", best_score)
        display(best_matches)
    return ranked

for search_text in ["how to pay fee", "reset password"]:
    print("Query:", search_text)
    score_faq_entries_v2(search_text, df_faq)

Executing search for tie query: 'how to pay fee'

No tie detected. Single best match found with score 3.

,question,answer,keywords,category,confidence_score
0,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing,3

Executing search for single winner query: 'reset password'

No tie detected. Single best match found with score 2.

,question,answer,keywords,category,confidence_score
0,how to reset password,Go to Settings > Reset Password.,password reset login,account,2